/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PassManager;

import ConnectionsPK.DBconnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author SuperUser
 */
public class AccountSettingForm extends javax.swing.JInternalFrame {
    Connection con = null;
    //PreparedStatement stmt=null;
    Statement st = null;
    /**
     * Creates new form AccountSettingForm
     */
    public AccountSettingForm() {
        initComponents();
        //conection
        //con = DBconnection.connect();
        DBconnection conIns = DBconnection.getConnectionInstance();
        con = conIns.getConnection();
        getTable();
    }
    public void getTable(){
    String getdata;
    int id = 1;
    getdata = "SELECT * FROM admin where uID ='"+id+"' LIMIT 1";
    try
    {
        Statement stmt = con.createStatement();
        ResultSet rs = stmt.executeQuery(getdata);
        String u,p,e,r;
            while(rs.next())
            {
                u= rs.getString("username");
                p= rs.getString("password");
                e= rs.getString("email");
                //r= rs.getString("recovery");
                //Setting Values
                    unameBox.setText(u);
                    passwordBox.setText(p);
                    passwordcheck.setText("");
                    emailbox.setText(e);
                    //emailbox.setText(r);
            }    
 
    }
    catch(Exception ex)
    {
    System.out.println(ex);
    }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        unameBox = new javax.swing.JTextField();
        emailbox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        passwordBox = new javax.swing.JPasswordField();
        passwordcheck = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        confirmprogressBar = new javax.swing.JProgressBar();
        label = new javax.swing.JLabel();
        PasswordProgressBar = new javax.swing.JProgressBar();
        UserNameProgressBar = new javax.swing.JProgressBar();
        emailProgressBar = new javax.swing.JProgressBar();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        digits = new javax.swing.JPasswordField();
        savebtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(750, 550));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setOpaque(false);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username: ");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email: ");

        unameBox.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)));
        unameBox.setPreferredSize(new java.awt.Dimension(4, 20));
        unameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameBoxActionPerformed(evt);
            }
        });
        unameBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                unameBoxKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                unameBoxKeyTyped(evt);
            }
        });

        emailbox.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)));
        emailbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailboxActionPerformed(evt);
            }
        });
        emailbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailboxKeyReleased(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Confirm Password:");

        passwordBox.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)));
        passwordBox.setMinimumSize(new java.awt.Dimension(4, 20));
        passwordBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordBoxKeyReleased(evt);
            }
        });

        passwordcheck.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)));
        passwordcheck.setMinimumSize(new java.awt.Dimension(4, 20));
        passwordcheck.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordcheckKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwordcheckKeyTyped(evt);
            }
        });

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Manage Your Account");

        confirmprogressBar.setForeground(new java.awt.Color(0, 255, 255));
        confirmprogressBar.setToolTipText("Confirm Password");
        confirmprogressBar.setStringPainted(true);

        label.setBackground(new java.awt.Color(255, 255, 255));
        label.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        label.setForeground(new java.awt.Color(0, 0, 153));

        PasswordProgressBar.setForeground(new java.awt.Color(0, 255, 255));
        PasswordProgressBar.setToolTipText("Confirm Password");
        PasswordProgressBar.setStringPainted(true);

        UserNameProgressBar.setForeground(new java.awt.Color(0, 255, 255));
        UserNameProgressBar.setToolTipText("Confirm Password");
        UserNameProgressBar.setStringPainted(true);

        emailProgressBar.setForeground(new java.awt.Color(0, 255, 255));
        emailProgressBar.setToolTipText("Confirm Password");
        emailProgressBar.setStringPainted(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(63, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(40, 40, 40))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(emailbox)
                                    .addComponent(passwordcheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(unameBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(passwordBox, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(confirmprogressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PasswordProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UserNameProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {passwordBox, unameBox});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {PasswordProgressBar, UserNameProgressBar, confirmprogressBar, emailProgressBar});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(unameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UserNameProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passwordBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(PasswordProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordcheck, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(confirmprogressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(emailbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addContainerGap(42, Short.MAX_VALUE))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {PasswordProgressBar, UserNameProgressBar, confirmprogressBar, emailProgressBar, emailbox, jLabel1, jLabel2, jLabel3, jLabel4, passwordBox, passwordcheck, unameBox});

        getContentPane().add(jPanel1);
        jPanel1.setBounds(12, 12, 710, 278);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setOpaque(false);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Enter 4 digits for secure you Encryption: ");

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Security Options");

        digits.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        digits.setForeground(new java.awt.Color(255, 0, 0));
        digits.setBorder(null);

        savebtn.setText("Save");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(digits, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(savebtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(459, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(5, 5, 5)
                .addComponent(digits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(savebtn)
                .addContainerGap())
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 310, 710, 125);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Isura\\Documents\\NetBeansProjects\\PasswordManager\\BGp.png")); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, -20, 750, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void unameBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unameBoxActionPerformed

    private void emailboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailboxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // TODO add your handling code here:
        String uname = unameBox.getText();
        String pword = passwordBox.getText();
        String pwordCheck = passwordcheck.getText();
        String emailadd = emailbox.getText();
        int id=1;
        if(pword.equals(pwordCheck)){
                try
                {
                    String updateAcc ;
                    updateAcc ="UPDATE admin SET username='"+uname+"', password='"+pword+"', email='"+emailadd+"' WHERE uID = '"+id+"' ";
//                     updateAcc = "INSERT INTO admin"
//                                     +"(username,password,email,recovery)"
//                                        +"VALUES('"+uname+"','"+pword+"','"+emailadd+"','"+0000+"')";
//                     stmt = con.prepareStatement(updateAcc);
//                     stmt.execute();
                    st = con.createStatement();
                    st.executeUpdate(updateAcc);
                   //System.out.println("OK");
                   label.setText("Update Success!");
                }
                catch(Exception e)
                {
                    System.out.println(e);
                }        
        }else{System.out.println("Password not Matched");}

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void passwordcheckKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordcheckKeyTyped

    }//GEN-LAST:event_passwordcheckKeyTyped

    private void passwordcheckKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordcheckKeyReleased
        // TODO add your handling code here:
        String pword = passwordBox.getText();
        String pwordCheck = passwordcheck.getText();
        if(pword.equals(pwordCheck)){
        confirmprogressBar.setValue(100);
        }else{
        confirmprogressBar.setValue(0);
        }
    }//GEN-LAST:event_passwordcheckKeyReleased

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savebtnActionPerformed

    private void unameBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unameBoxKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_unameBoxKeyReleased

    private void unameBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unameBoxKeyTyped
        // TODO add your handling code here:
        String s =unameBox.getText();
        if(!s.isEmpty()&& s.length()>=3){
        UserNameProgressBar.setValue(100);
        }else{
        UserNameProgressBar.setValue(0);

        }
    }//GEN-LAST:event_unameBoxKeyTyped

    private void passwordBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordBoxKeyReleased
        // TODO add your handling code here:
        String s = passwordBox.getText();
        if(!s.isEmpty()){
            if(s.length()<=2){
            PasswordProgressBar.setValue(20);
            }else if(s.length()<=4){
            PasswordProgressBar.setValue(40);        
            }else if(s.length()<=6){
            PasswordProgressBar.setValue(60);                   
            }else if(s.length()>=7){
            PasswordProgressBar.setValue(100);                   
            }else{
            PasswordProgressBar.setValue(0);
            }
        }else{
            PasswordProgressBar.setValue(0);
        }
    }//GEN-LAST:event_passwordBoxKeyReleased

    private void emailboxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailboxKeyReleased
        // TODO add your handling code here:
      boolean tf;
      String email = emailbox.getText();
      String EMAIL_REGEX = "^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";
      tf = email.matches(EMAIL_REGEX);
      if(tf==true){
      emailProgressBar.setValue(100);
      }else{
          emailProgressBar.setValue(0);
      }
    }//GEN-LAST:event_emailboxKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar PasswordProgressBar;
    private javax.swing.JProgressBar UserNameProgressBar;
    private javax.swing.JProgressBar confirmprogressBar;
    private javax.swing.JPasswordField digits;
    private javax.swing.JProgressBar emailProgressBar;
    private javax.swing.JTextField emailbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label;
    private javax.swing.JPasswordField passwordBox;
    private javax.swing.JPasswordField passwordcheck;
    private javax.swing.JButton savebtn;
    private javax.swing.JTextField unameBox;
    // End of variables declaration//GEN-END:variables
}
